steps:
  scrape_nhs_data:
    enable_cache: False
  scrape_mind_data:
    enable_cache: False
  version_data:
    enable_cache: False
    parameters:
      data_version_name: "second_version"
      filename_roots: ["mind_data_raw", "nhs_data_raw"]
      debug_mode: False
