apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: llm
  namespace: matcha-seldon-workloads
spec:
  protocol: v2
  predictors:
  - graph:
      name: transformer
      implementation: HUGGINGFACE_SERVER
      parameters:
      - name: task
        type: STRING
        value: summarization
      - name: pretrained_model
        type: STRING
        value: google/flan-t5-small
    name: default
    replicas: 1